apiVersion: v1 # In which version of kubernetes was the below kind of resource introduced - In our case the resource is pod and it was introduced in v1
kind: Pod # Kind of resource this manifest is used for 
metadata:
  name: nginx # name of the pod
spec:
  containers:
  - name: nginx # name of the container
    image: nginx # image name in docker hub
    ports:
    - containerPort: 80 # This actually does nothing written here for doc purpose


# To apply this manifest i.e start the pod using nginx in it we run the command `kubectl apply -f pod.yml`  

# Can use `kubectl run nginx --image=nginx --port=80` to run using CLI

# A cluster contains many nodes (master and worker) and a node can contain many pods and a pod can run one or more containers in it.
