kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30007 # Port on which the service is exposed inside the container
    hostPort: 30007 # Expose service on localhost:30007
- role: worker
- role: worker
